user-agentを追加
pokepay/partner-php-sdk pull request #56
Opened 2024-07-03 09:31 UTC by cxxxr

2024-07-03 14:21 UTC, tsasao requested changes

2024-07-03 14:21 UTC, tsasao commented on lib/PartnerAPI.php
> +    private function computeUserAgent() {
メソッド名に反して、HTTPヘッダ名と:と値が連結された値が返ってくるのは、なんとかした方が良い。
端的に言えば、 `User-Agent: ` を返す必要はない。

2024-07-03 14:21 UTC, tsasao commented on lib/PartnerAPI.php
> +        array_push($headers, 'User-Agent: ' . 'partner-php-sdk/' . self::VERSION);
同じキーのヘッダを2つ設定する意図がよくわからない。

2024-07-03 14:21 UTC, tsasao commented on config.ini.sample
> +APP_VERSION  = '0.0.0'
普通に考えるとアプリバージョンは、ここではないどこかで設定されているだろうから、pokepayのconfigで設定するというよりは、$client->setAppVersion($app->getVersion())的なコードになるのが自然では？

2024-07-03 14:21 UTC, tsasao commented on lib/PartnerAPI.php
> +            $userAgent = $userAgent . $this->appVersion . ' ';
appNameとappVersionは空白区切りなのでしょうか？
また、appNameが未設定でappVersionだけがある、とか、そういうケースで変なものがセットされるくらいなら、無視するなりエラーなりの方が良いのでは？

2024-07-03 14:21 UTC, tsasao commented on lib/PartnerAPI.php
> +            if (array_key_exists('APP_NAME', $config)) {
未設定でも、unknown/0.0.0みたいなのを返した方が、サーバログ的にはparseしやすくて嬉しいような気がします。

2024-07-04 05:19 UTC, cxxxr commented on config.ini.sample
> +APP_VERSION  = '0.0.0'
ACCEPT_LANGUAGEとの一貫性を持たせたかったんですが、メソッドの方も追加しました

2024-07-04 05:19 UTC, cxxxr commented on lib/PartnerAPI.php
> +        array_push($headers, 'User-Agent: ' . 'partner-php-sdk/' . self::VERSION);
これは消し忘れでした

2024-07-04 07:05 UTC, tsasao approved these changes
LGTM!

2024-09-12 10:27 UTC, merged